### ISSUE TITLE
Created jar doesn't contain the apache license and doesn't contain the asm license

### ISSUE THREAD

**Issue by cgoudie** [kantega/notsoserial#12]
http://asm.ow2.org/license.html
https://github.com/kantega/notsoserial/blob/master/LICENSE

Both probably should be included in the published jar

**Comment by cgoudie** [comment]
META-INF/maven/org.kantega/notsoserial/pom.xml does have the apache license. Could you also add the ASM license for proper compliance?

**Comment by eirbjo** [comment]
I have created pull request #13 for this.

I have added a &lt;license&gt; to the pom, added a LICENCE-ASM file in the source, included LICENSE, LICENSE-ASM as files in META-INF in the jar distribution and finally I added a NOTICE file including an attribution to ASM.

 Can you take a look and see if anything is missing?

**Comment by cgoudie** [comment]
At a cursory glance, it looks good. The only licenses I saw that were relevant were the ASM and Apache ones.

I also appreciate the limiting of ASM to just what is necessary

**Comment by eirbjo** [comment]
Great, I'll close #13
