### ISSUE TITLE
CustomNotSoSerialIT failing on Windows

### ISSUE THREAD

**Issue by anderius** [kantega/notsoserial#17]
Tests in error:

```
CustomNotSoSerialIT.before:50 » InvalidPath Illegal char <:> at index 2: /C:/U...
CustomNotSoSerialIT.after:56 » NullPointer
```

**Comment by eirbjo** [comment]
Btw, have you also tested that the agent actually loads on Windows?

**Comment by anderius** [comment]
I have not, I only fixed the failing test. I guessed some of the integration tests did that?

**Comment by eirbjo** [comment]
Aha. Yes. But they do it using attach. So a command line specified agent will execute a slightly different code path.

**Comment by anderius** [comment]
Maybe we can open a separate issue for testing that? This issue is fixed, and tested on Windows.
